title: "[NAME THE PACKAGE]"
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: "The raw idea, a use case, or something we’ve seen that motivates us to work on this."
    validations:
      required: true
  - type: dropdown
    id: appetite
    attributes:
      label: The appetite
      description: " How much time we want to spend and how that constrains the solution."
      options:
        - Small (2 to 3 weeks)
        - Big (6 weeks)
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The solution
      description: "The core elements we came up with, presented in a form that’s easy for people to immediately understand."
    validations:
      required: true    
  - type: textarea
    id: risks
    attributes:
      label: Risks & Rabbit holes
      description: "Details about the solution worth calling out to avoid problems."
    validations:
      required: true
  - type: textarea
    id: no-gos
    attributes:
      label: No gos
      description: "Anything specifically excluded from the concept: functionality or use cases we intentionally aren’t covering to fit the appetite or make the problem tractable."
    validations:
      required: true
      
      
      
      
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
