title: "[NAME THE PACKAGE]"
body:
 - type: textarea
    id: requirements
    attributes:
      label: The requirements
      description: "The list of the requirements addressed in the discussion."
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: "The raw idea, a use case, or something we’ve seen that motivates us to work on this."
    validations:
      required: true
  - type: dropdown
    id: appetite
    attributes:
      label: The appetite
      description: " How much time we want to spend and how that constrains the solution."
      options:
        - Small (2 to 3 weeks)
        - Big (6 weeks)
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The solution
      description: "The core elements we came up with, presented in a form that’s easy for people to immediately understand."
    validations:
      required: true    
  - type: textarea
    id: risks
    attributes:
      label: Risks & Rabbit holes
      description: "Details about the solution worth calling out to avoid problems."
      value: |
        ## Technical Unknowns
        ## Unsolved Design Problems
        And some more markdown
    validations:
      required: true
  - type: textarea
    id: no-gos
    attributes:
      label: No gos
      description: "Anything specifically excluded from the concept: functionality or use cases we intentionally aren’t covering to fit the appetite or make the problem tractable."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
